"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import bosdyn.api.payload_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PayloadEstimationCommand(google.protobuf.message.Message):
    """Command the robot to stand and execute a routine to estimate the mass properties of an
    unregistered payload attached to the robot.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Request(google.protobuf.message.Message):
        """PayloadEstimation command request takes no additional arguments. The estimation routine
        takes about ~1min to run. Subsequent PayloadEstimationCommand requests issued while the 
        routine is in progress are ignored until the routine is completed.
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        def __init__(self,
            ) -> None: ...

    class Feedback(google.protobuf.message.Message):
        """The PayloadEstimationCommand provides several pieces of feedback:
          - If the routine is finished running (and its current progress).
          - If the routine encountered any errors while running.
          - The resulting payload estimated by the routine.
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class _Status:
            ValueType = typing.NewType('ValueType', builtins.int)
            V: typing_extensions.TypeAlias = ValueType
        class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PayloadEstimationCommand.Feedback._Status.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            STATUS_UNKNOWN: PayloadEstimationCommand.Feedback._Status.ValueType  # 0
            STATUS_COMPLETED: PayloadEstimationCommand.Feedback._Status.ValueType  # 1
            """Completed estimation routine successfully; estimated_payload is populated."""

            STATUS_SMALL_MASS: PayloadEstimationCommand.Feedback._Status.ValueType  # 2
            """Completed estimation routine successfully, but estimated mass is small enough to
            not significantly impact mobility; estimated_payload is empty.
            """

            STATUS_IN_PROGRESS: PayloadEstimationCommand.Feedback._Status.ValueType  # 3
            """Estimation routine is currently running; estimated_payload is empty."""

            STATUS_ERROR: PayloadEstimationCommand.Feedback._Status.ValueType  # 4
            """Error occurred during the routine; estaimted_payload is empty."""

        class Status(_Status, metaclass=_StatusEnumTypeWrapper):
            pass

        STATUS_UNKNOWN: PayloadEstimationCommand.Feedback.Status.ValueType  # 0
        STATUS_COMPLETED: PayloadEstimationCommand.Feedback.Status.ValueType  # 1
        """Completed estimation routine successfully; estimated_payload is populated."""

        STATUS_SMALL_MASS: PayloadEstimationCommand.Feedback.Status.ValueType  # 2
        """Completed estimation routine successfully, but estimated mass is small enough to
        not significantly impact mobility; estimated_payload is empty.
        """

        STATUS_IN_PROGRESS: PayloadEstimationCommand.Feedback.Status.ValueType  # 3
        """Estimation routine is currently running; estimated_payload is empty."""

        STATUS_ERROR: PayloadEstimationCommand.Feedback.Status.ValueType  # 4
        """Error occurred during the routine; estaimted_payload is empty."""


        class _Error:
            ValueType = typing.NewType('ValueType', builtins.int)
            V: typing_extensions.TypeAlias = ValueType
        class _ErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PayloadEstimationCommand.Feedback._Error.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            ERROR_UNKNOWN: PayloadEstimationCommand.Feedback._Error.ValueType  # 0
            ERROR_NONE: PayloadEstimationCommand.Feedback._Error.ValueType  # 1
            """No error has occurred."""

            ERROR_FAILED_STAND: PayloadEstimationCommand.Feedback._Error.ValueType  # 2
            """Robot failed to stand/change stance."""

            ERROR_NO_RESULTS: PayloadEstimationCommand.Feedback._Error.ValueType  # 3
            """Failed to calculate results."""

        class Error(_Error, metaclass=_ErrorEnumTypeWrapper):
            pass

        ERROR_UNKNOWN: PayloadEstimationCommand.Feedback.Error.ValueType  # 0
        ERROR_NONE: PayloadEstimationCommand.Feedback.Error.ValueType  # 1
        """No error has occurred."""

        ERROR_FAILED_STAND: PayloadEstimationCommand.Feedback.Error.ValueType  # 2
        """Robot failed to stand/change stance."""

        ERROR_NO_RESULTS: PayloadEstimationCommand.Feedback.Error.ValueType  # 3
        """Failed to calculate results."""


        STATUS_FIELD_NUMBER: builtins.int
        PROGRESS_FIELD_NUMBER: builtins.int
        ERROR_FIELD_NUMBER: builtins.int
        ESTIMATED_PAYLOAD_FIELD_NUMBER: builtins.int
        status: global___PayloadEstimationCommand.Feedback.Status.ValueType
        """Status of the estimation routine."""

        progress: builtins.float
        """The approximate progress of the routine, range [0-1]."""

        error: global___PayloadEstimationCommand.Feedback.Error.ValueType
        """Error status of the estimation routine."""

        @property
        def estimated_payload(self) -> bosdyn.api.payload_pb2.Payload:
            """The resulting payload estimated by the estimation routine."""
            pass
        def __init__(self,
            *,
            status: global___PayloadEstimationCommand.Feedback.Status.ValueType = ...,
            progress: builtins.float = ...,
            error: global___PayloadEstimationCommand.Feedback.Error.ValueType = ...,
            estimated_payload: typing.Optional[bosdyn.api.payload_pb2.Payload] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["estimated_payload",b"estimated_payload"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["error",b"error","estimated_payload",b"estimated_payload","progress",b"progress","status",b"status"]) -> None: ...

    def __init__(self,
        ) -> None: ...
global___PayloadEstimationCommand = PayloadEstimationCommand
