"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import bosdyn.api.geometry_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StairTransform(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FRAME_TFORM_STAIRS_FIELD_NUMBER: builtins.int
    FRAME_NAME_FIELD_NUMBER: builtins.int
    @property
    def frame_tform_stairs(self) -> bosdyn.api.geometry_pb2.SE3Pose:
        """The staircase origin is the bottom-center of the first rise."""
        pass
    frame_name: typing.Text
    def __init__(self,
        *,
        frame_tform_stairs: typing.Optional[bosdyn.api.geometry_pb2.SE3Pose] = ...,
        frame_name: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["frame_tform_stairs",b"frame_tform_stairs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["frame_name",b"frame_name","frame_tform_stairs",b"frame_tform_stairs"]) -> None: ...
global___StairTransform = StairTransform

class StraightStaircase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Stair(google.protobuf.message.Message):
        """A single stair from a staircase."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        RISE_FIELD_NUMBER: builtins.int
        RUN_FIELD_NUMBER: builtins.int
        rise: builtins.float
        """Height of each stair."""

        run: builtins.float
        """Depth of each stair."""

        def __init__(self,
            *,
            rise: builtins.float = ...,
            run: builtins.float = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["rise",b"rise","run",b"run"]) -> None: ...

    class Landing(google.protobuf.message.Message):
        """Straight staircases have two landings, one at the top and one at the bottom.
        Landings are areas of free space before and after the stairs, and are represented
        as oriented bounding boxes.
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STAIRS_TFORM_LANDING_CENTER_FIELD_NUMBER: builtins.int
        LANDING_EXTENT_X_FIELD_NUMBER: builtins.int
        LANDING_EXTENT_Y_FIELD_NUMBER: builtins.int
        @property
        def stairs_tform_landing_center(self) -> bosdyn.api.geometry_pb2.SE3Pose:
            """Pose of the landing's center relative to the stairs frame."""
            pass
        landing_extent_x: builtins.float
        """The half-size of the box representing the landing in the x axis."""

        landing_extent_y: builtins.float
        """The half-size of the box representing the landing in the y axis."""

        def __init__(self,
            *,
            stairs_tform_landing_center: typing.Optional[bosdyn.api.geometry_pb2.SE3Pose] = ...,
            landing_extent_x: builtins.float = ...,
            landing_extent_y: builtins.float = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["stairs_tform_landing_center",b"stairs_tform_landing_center"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["landing_extent_x",b"landing_extent_x","landing_extent_y",b"landing_extent_y","stairs_tform_landing_center",b"stairs_tform_landing_center"]) -> None: ...

    FROM_KO_TFORM_STAIRS_FIELD_NUMBER: builtins.int
    TFORM_FIELD_NUMBER: builtins.int
    STAIRS_FIELD_NUMBER: builtins.int
    BOTTOM_LANDING_FIELD_NUMBER: builtins.int
    TOP_LANDING_FIELD_NUMBER: builtins.int
    @property
    def from_ko_tform_stairs(self) -> bosdyn.api.geometry_pb2.SE3Pose:
        """It is expressed in ko frame of the from_waypoint.
        This field is only used in GraphNav.
        """
        pass
    @property
    def tform(self) -> global___StairTransform:
        """Outside GraphNav, this field specifies the stair origin."""
        pass
    @property
    def stairs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StraightStaircase.Stair]:
        """Each stair should be rise followed by run. The last stair will have zero run."""
        pass
    @property
    def bottom_landing(self) -> global___StraightStaircase.Landing:
        """The lowermost landing of the stairs. The robot will try to
        align itself to the stairs while on this landing.
        """
        pass
    @property
    def top_landing(self) -> global___StraightStaircase.Landing:
        """The uppermost landing of the stairs."""
        pass
    def __init__(self,
        *,
        from_ko_tform_stairs: typing.Optional[bosdyn.api.geometry_pb2.SE3Pose] = ...,
        tform: typing.Optional[global___StairTransform] = ...,
        stairs: typing.Optional[typing.Iterable[global___StraightStaircase.Stair]] = ...,
        bottom_landing: typing.Optional[global___StraightStaircase.Landing] = ...,
        top_landing: typing.Optional[global___StraightStaircase.Landing] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bottom_landing",b"bottom_landing","from_ko_tform_stairs",b"from_ko_tform_stairs","location",b"location","tform",b"tform","top_landing",b"top_landing"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bottom_landing",b"bottom_landing","from_ko_tform_stairs",b"from_ko_tform_stairs","location",b"location","stairs",b"stairs","tform",b"tform","top_landing",b"top_landing"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["location",b"location"]) -> typing.Optional[typing_extensions.Literal["from_ko_tform_stairs","tform"]]: ...
global___StraightStaircase = StraightStaircase
