"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import bosdyn.api.arm_command_pb2
import bosdyn.api.gripper_command_pb2
import bosdyn.api.mobility_command_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SynchronizedCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Request(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ARM_COMMAND_FIELD_NUMBER: builtins.int
        MOBILITY_COMMAND_FIELD_NUMBER: builtins.int
        GRIPPER_COMMAND_FIELD_NUMBER: builtins.int
        @property
        def arm_command(self) -> bosdyn.api.arm_command_pb2.ArmCommand.Request: ...
        @property
        def mobility_command(self) -> bosdyn.api.mobility_command_pb2.MobilityCommand.Request: ...
        @property
        def gripper_command(self) -> bosdyn.api.gripper_command_pb2.GripperCommand.Request: ...
        def __init__(self,
            *,
            arm_command: typing.Optional[bosdyn.api.arm_command_pb2.ArmCommand.Request] = ...,
            mobility_command: typing.Optional[bosdyn.api.mobility_command_pb2.MobilityCommand.Request] = ...,
            gripper_command: typing.Optional[bosdyn.api.gripper_command_pb2.GripperCommand.Request] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["arm_command",b"arm_command","gripper_command",b"gripper_command","mobility_command",b"mobility_command"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["arm_command",b"arm_command","gripper_command",b"gripper_command","mobility_command",b"mobility_command"]) -> None: ...

    class Feedback(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ARM_COMMAND_FEEDBACK_FIELD_NUMBER: builtins.int
        MOBILITY_COMMAND_FEEDBACK_FIELD_NUMBER: builtins.int
        GRIPPER_COMMAND_FEEDBACK_FIELD_NUMBER: builtins.int
        @property
        def arm_command_feedback(self) -> bosdyn.api.arm_command_pb2.ArmCommand.Feedback: ...
        @property
        def mobility_command_feedback(self) -> bosdyn.api.mobility_command_pb2.MobilityCommand.Feedback: ...
        @property
        def gripper_command_feedback(self) -> bosdyn.api.gripper_command_pb2.GripperCommand.Feedback: ...
        def __init__(self,
            *,
            arm_command_feedback: typing.Optional[bosdyn.api.arm_command_pb2.ArmCommand.Feedback] = ...,
            mobility_command_feedback: typing.Optional[bosdyn.api.mobility_command_pb2.MobilityCommand.Feedback] = ...,
            gripper_command_feedback: typing.Optional[bosdyn.api.gripper_command_pb2.GripperCommand.Feedback] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["arm_command_feedback",b"arm_command_feedback","gripper_command_feedback",b"gripper_command_feedback","mobility_command_feedback",b"mobility_command_feedback"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["arm_command_feedback",b"arm_command_feedback","gripper_command_feedback",b"gripper_command_feedback","mobility_command_feedback",b"mobility_command_feedback"]) -> None: ...

    def __init__(self,
        ) -> None: ...
global___SynchronizedCommand = SynchronizedCommand
